"""Add models

Revision ID: ad064b21c72e
Revises: 253044ab85a6
Create Date: 2024-02-18 22:30:50.372539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad064b21c72e'
down_revision: Union[str, None] = '253044ab85a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    op.create_foreign_key(None, 'books', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    op.drop_column('books', 'genre_id')
    # ### end Alembic commands ###
